[[bin]]
name = "orchestrator"
path = "orchestrator.rs"

[package]
name = "orchestrator"
version = "0.1.0"
authors = ["Emir. D", "Dilawar. M", "Håvard. M"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"